name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Saxon
      run: make saxonjar

    - name: Run Makefile
      run: make ci saxpath=lib/saxon.jar

    - name: Push HTML
      run: |
        git config --global user.name 'Julian's HTML Bot'
        git config --global user.email 'julian.reschke@gmx.de'
        git commit -m "HTML checkin" draft-ietf-httpbis*.html
        git push
